### ISSUE TITLE
Add reference to mdast readme

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/mdast-util-from-adf#19]
The [mdast](https://github.com/syntax-tree/mdast) readme features a list of utility packages:
https://github.com/syntax-tree/mdast#list-of-utilities

It'd be nice to add this one there so people can discover it.

#18 should maybe be resolved before.

**Comment by klappradla** [comment]
https://github.com/syntax-tree/mdast/pull/40 ⏳
